### ISSUE TITLE
[FEATURE] Add china hat module

### ISSUE THREAD

**Issue by NathanKassab** [danny-125/Peroxide#5]
China hat is the best module, here is the code if you don't/can't make it. I give you permission to skid it since I believe that every client should have a china hat 😎. You don't even need to credit me, seeing china hat is enough for me to be happy 😄 

https://gist.github.com/NathanKassab/b8e320cc1c3c5a60dbc5808f2547b800

**Comment by danny-125** [comment]
Thanks for the suggestion but I don't really see the need for this module and if you really want it you can fork the client and make a pull request if you really want to see a china hat module, thanks anyways.

**Comment by MelonsYum** [comment]
nooo add china hat
