### ISSUE TITLE
[BUG] Killaura sends two combat packets

### ISSUE THREAD

**Issue by NathanKassab** [danny-125/Peroxide#6]
In the killaura module you send a c02 packet and then call another method that sends another c02 packet, that is not normal behavior and may flag some anticheats

Removing this line of code should fix this

https://github.com/danny-125/Peroxide/blob/0006b08f0a792be2321ed2ae306f419543dd4c5f/me/danny125/peroxide/modules/combat/TempKillAura.java#L164

**Comment by danny-125** [comment]
Thanks for the contribution, I will add it and credit you.
