### ISSUE TITLE
[FEATURE] Explosion compatible velocity

### ISSUE THREAD

**Issue by NathanKassab** [danny-125/Peroxide#8]
Currently the velocity only supports s12 packets, this will not work on hypixel since they use s27 packets. The difference between the two is one renders an explosion and adds to the motion instead of setting it, while the other only sets the motion. Inside of the S27PacketExplosion class there are three floats that determine the motion values, they are field_149152_f, field_149153_g and field_149159_h. Just make these public and change the values the same way you did for the s12 packets

Here are the lines to make public
https://github.com/danny-125/Peroxide/blob/f3542effa05916656656388a90da460186d13d17/net/minecraft/network/play/server/S27PacketExplosion.java#L21

And here is where you should change the values
https://github.com/danny-125/Peroxide/blob/3dcef04ba7c00cb925ddab6c127c20ec84205353/me/danny125/peroxide/modules/player/AntiKnockback.java#L24

**Comment by danny-125** [comment]
thanks for this, ill add it soon, ill keep this issue open so i dont forget
